### ISSUE TITLE
Availability on BioConda 

### ISSUE THREAD

**Issue by lecorguille** [jodyhey/IMa3#6]
Hi IMa3 Team,

I'm managing computing infrastructures in France. One of my colleague request me to install your tool.
For maintainability and reproducibility, we only install tools from Conda (and Singularity).

Have you ever thinking about providing OrientAGraph as a Conda package?

If you start a package on [bioconda](https://github.com/bioconda/bioconda-recipes), I can help you if you need.
Here is some help for software written in C: https://bioconda.github.io/contributor/guidelines.html#c-c

All the best

**Comment by jodyhey** [comment]
The build is pretty easy so long as there is a recent compiler with Open MPI.   However I don't have the time now to make a conda package

**Comment by lecorguille** [comment]
Easy on a single personal computer. But as soon as you have to deal with more than 400 scientific tools that need plenty of dependencies in precise versions not compatible with each other... 
You have to install the tools with a package manager.  In our case, we choose Conda and Singularity.

Correctly packaging a tool allow its availability for several year for reproducibility purpose.

I will do it!
Can you at least create a tag with a version number?

**Comment by jodyhey** [comment]
Thanks.  I just created a tag and release on github.    


    On Wednesday, September 15, 2021, 11:15:32 AM EDT, Gildas Le Corguillé ***@***.***> wrote:  
 
 


Easy on a single personal computer. But as soon as you have to deal with more than 400 scientific tools that need plenty of dependencies in precise versions not compatible with each other...
You have to install the tools with a package manager. In our case, we choose Conda and Singularity.

Correctly packaging a tool allow its availability for several year for reproducibility purpose.

I will do it!
Can you at least create a tag with a version number?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lecorguille** [comment]
Oh, and can you provide a Licence for the code otherwise Bioconda won't accept it.

**Comment by lecorguille** [comment]
The package is ready (I tested the build locally) : https://github.com/bioconda/bioconda-recipes/pull/30567
To finalize it now I need a LICENSE file.

**Comment by jodyhey** [comment]
Thanks for doing this.   To be clear,  you are talking about a license file that I would add to the github repository?
    On Thursday, September 16, 2021, 10:35:19 AM EDT, Gildas Le Corguillé ***@***.***> wrote:  
 
 


The package is ready (I tested the build locally) : bioconda/bioconda-recipes#30567
To finalize it now I need a LICENSE file.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lecorguille** [comment]
> To be clear,  you are talking about a license file that I would add to the github repository?

Exactly, an MIT or GLPv3 for example, that allow to re-distribute the software.

**Comment by jodyhey** [comment]
A license has been added. 


    On Sunday, September 19, 2021, 10:55:20 AM EDT, Gildas Le Corguillé ***@***.***> wrote:  
 
 



To be clear, you are talking about a license file that I would add to the github repository?


Exactly, an MIT or GLPv3 for example, that allow to re-distribute the software.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lecorguille** [comment]
We are close.
Can you refresh your tag with the last commit of the master which include the LICENSE file. 

Sorry for this confusion. I should have request the LICENSE first, then the tag :/

**Comment by jodyhey** [comment]
not sure if I did it right,  but I committed with a new tag and release v1.12
    On Thursday, September 23, 2021, 08:56:36 AM EDT, Gildas Le Corguillé ***@***.***> wrote:  
 
 


We are close.
Can you refresh your tag with the last commit of the master which include the LICENSE file.

Sorry for this confusion. I should have request the LICENSE first, then the tag :/

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lecorguille** [comment]
I would suggest you to delete the tag 1.11 or named a new one 1.11.1, otherwise you will have a shift between your software version and the github tag.

**Comment by jodyhey** [comment]
I deleted 1.11
    On Friday, September 24, 2021, 04:19:56 AM EDT, Gildas Le Corguillé ***@***.***> wrote:  
 
 


I would suggest you to delete the tag 1.11 or named a new one 1.11.1, otherwise you will have a shift between your software version and the github tag.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
